-- Total Orders
SELECT COUNT(DISTINCT ORDERNUMBER) AS TOTAL_ORDERS
FROM `azmary.Sales_data.sales`;

-- Unique Customers
SELECT COUNT(DISTINCT CUSTOMERNAME) AS UNIQUE_CUSTOMERS
FROM `azmary.Sales_data.sales`;

-- Customer Region
SELECT COUNTRY, COUNT(DISTINCT CUSTOMERNAME) AS TOTAL_CUSTOMERS
FROM `azmary.Sales_data.sales`
GROUP BY COUNTRY
ORDER BY TOTAL_CUSTOMERS DESC;

-- Average Order Value
SELECT ROUND(SUM(SALES) / COUNT(DISTINCT ORDERNUMBER), 2) AS AVG_ORDER_VALUE
FROM `azmary.Sales_data.sales`;

-- Top Customers by Total Sales
SELECT CUSTOMERNAME, ROUND(SUM(SALES), 2) AS TOTAL_SALES
FROM `azmary.Sales_data.sales`
GROUP BY CUSTOMERNAME
ORDER BY TOTAL_SALES DESC
LIMIT 10;

-- Most Frequently Ordering Customers
SELECT CUSTOMERNAME, COUNT(DISTINCT ORDERNUMBER) AS TOTAL_ORDERS
FROM `azmary.Sales_data.sales`
GROUP BY CUSTOMERNAME
ORDER BY TOTAL_ORDERS DESC
LIMIT 10;

-- Most Popular Order Days
SELECT FORMAT_DATE('%A', ORDERDATE) AS DAY_NAME,
       COUNT(*) AS TOTAL_ORDERS
FROM `azmary.Sales_data.sales`
GROUP BY DAY_NAME
ORDER BY TOTAL_ORDERS DESC;

-- Total Sales and Quantity
SELECT 
  ROUND(SUM(SALES), 2) AS TOTAL_SALES,
  SUM(QUANTITYORDERED) AS TOTAL_QUANTITY
FROM `azmary.Sales_data.sales`;
